# Site settings
title: pebble {code}
email: hello@pebblecode.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Innovation Consultancy - Agile Development, Design Thinking and Rapid Prototyping.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pebblecode.com" # the base hostname & protocol for your site
twitter: pebblecode
github:  pebblecode
vimeo:  pebblecode


# Build settings
incremental: true
exclude: [node_modules, _js, _stylesheets]
markdown: kramdown
redirects: yes
permalink: "/blog/:title/"


# Pagination
paginate: 8
paginate_path: "/blog/:num"

relative_permalinks: false

#tag blog posts for analytics
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      analytics_category: "blog"

gems:
  - jekyll-paginate
  - jekyll-sitemap
